Rename ImGuiKey_KeyPadEnter to ImGuiKey_KeypadEnter
Fixes compilation error with dear dear imgui, v1.91.5:

> error: use of undeclared identifier 'ImGuiKey_KeyPadEnter'; did you mean 'ImGuiKey_KeypadEnter'?

The method name was changed in v1.90.1
https://github.com/ocornut/imgui/releases/tag/v1.90.1